server:
  error:
    include-stacktrace: never

aws:
  s3:
    region:
      name: eu-west-3
    bucket:
      name: image-uploader-elliot

spring:
  servlet:
    multipart:
      max-file-size: 500MB