name: CI

on:
  push:
    branches:
      - main

jobs:
  java-build:
    name: Spring Boot CI
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: Maven Build
        run: mvn --batch-mode --update-snapshots verify

  angular-build:
    name: Angular CI
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src/frontend/image-uploader-front

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build:prod

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test:prod